version: "3.5"

services:
  server:
    image: judge0/judge0:1.13.1
    volumes:
      - ./judge0.conf:/judge0.conf:ro
      - type: bind
        source: ../backend/src/problems
        target: /dev/problems
    ports:
      - "2358:2358"
    privileged: true
    restart: always
    logging:
      driver: none

  workers:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
      - type: bind
        source: ../backend/src/problems
        target: /dev/problems
    privileged: true
    restart: always
    logging:
      driver: none

  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    restart: always
    logging:
      driver: none

  redis:
    image: redis:7.2.4
    command:
      [
        "bash",
        "-c",
        'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"',
      ]
    env_file: judge0.conf
    restart: always
    volumes:
      - cache:/data
    logging:
      driver: none

volumes:
  data:
  cache:
    driver: local
